replicaCount: 5

image:
  repository: zpechinger/prom-test-app
  tag: 0.0.2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

serviceMonitor:
  enabled: true
  interval: 15s

prometheus:
  address: http://kube-prometheus-stack-prometheus.prometheus:9090
