apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prom-test-app.fullname" . }}
  labels:
    app: {{ include "prom-test-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "prom-test-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "prom-test-app.name" . }}
    spec:
      containers:
        - name: prom-test-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /metrics
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /metrics
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
